### PR TITLE
Add support for array matching

### LINKED ISSUE #7: Array support
simply matching  values, I think it would be very cool to be as powerful as elixir binary patterns later

### PR DESCRIPTION
**Pull request by haltcase**
Closes #7

Extract seq logic and reuse for arrays.

~~However there's a Nim bug preventing this from working right now. Array bounds checking isn't deactivated as it should be so if a pattern has a greater length than the input, you'll get an index error.~~

I'm also getting unrelated failures because of `maybeMatches`... there's something up with its return type I think.

### CODE REVIEW

**Comment by haltcase** [comment]
Solution to the bounds check issue may be to use `when arr.len >= n`. The naive approach of just wrapping the entire condition with that doesn't work though because any captured variables will only be available in one branch of the `when` block. That makes them become undeclared to the code that uses them when the array is smaller than `n`.

@alehander42 any thoughts on what to generate to fix this?

**Comment by alehander92** [comment]
when should be separated: 
when length check:
  normal check
else:
  false

**Comment by alehander92** [comment]
your whole check becomes a "when", and each wen resolves to a normal check without length

**Comment by alehander92** [comment]
very confusing, but a pattern I had to use for many features

**Comment by haltcase** [comment]
It might be more complicated than that. What if two branches have the same array length? The first `when arr.len >= n` is going to prevent a later branch from being checked.

It's also not as simple as:

```nim
if isArray:
  quote do:
    when `minTest`: `t` else: false
else:
  quote do: `minTest` and `t`
```

... because you'll get `undeclared identifier` in the array case if `minTest` is false and you've captured any variables.

Simplest solution I can think of right now is to essentially declare dummy variables in the falsy case just to satisfy the compiler (would that sometimes be horribly inefficient?). Might be able to use the existing `assignNames` data for that, but it doesn't include the type.

**Comment by alehander92** [comment]
no, it's a very simple change: we keep the if-s for each branch, this is not going to happen

we will generate

if (when len >= 2: a[2] == 2 else: false):

elif (when .. ):

**Comment by alehander92** [comment]
this is exactly how some other checks work:  they generate something like

if (when stuff is enum .. elif stuff is object .. ):

**Comment by alehander92** [comment]
basically 

if LEN and TEST

=>

if (when LEN: TEST else: false)

as I said, kinda confusing, but it works

you'll notice you won't accidentally prevent other branches

**Comment by haltcase** [comment]
> if (when LEN: TEST else: false)

Unless I'm missing something that won't work, I tried that already. Captured variables are only declared in `TEST`, so the compiler throws an error because code within the if branch uses those variables but they aren't declared unless the `LEN` check is true at compile time.

**Comment by alehander92** [comment]
but this shouldn't be what is really happening.

`when` should happen before sempass, so if false should be dead code: can you give me the example pattern again?

**Comment by haltcase** [comment]
I've been testing with this:

```nim
let nums = [1, 2]

match nums:
  [1, 2, @a]: echo "1, 2, then ", $a
  [1, 2]: echo "1 & 2"
  _: echo "no match"
```

**Comment by alehander92** [comment]
ah I see, you're right

**Comment by alehander92** [comment]
Ok, I fixed it: it's a little bit ugly maybe.

Basically newCode is used to maintain additional code to be added in the body. However I started defining variables inside the test, so I don't use it so much now, but we use it here to pass a `when test`: so if we see this in the branch, we know to put the code also in when.

Basically we generate

if (when ..):
  when LEN:
    ..

**Comment by alehander92** [comment]
If you want, I can merge the PR and add this additional fix

**Comment by haltcase** [comment]
> If you want, I can merge the PR and add this additional fix

@alehander42 great, feel free! You should be able to push to my branch before merging.

**Comment by alehander92** [comment]
Ok, so this should work now on master, thank you!!

**Pull request merged**
